# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escenario', models.CharField(max_length=200)),
                ('tipo_escenario', models.CharField(choices=[('O', 'Operativo'), ('A', 'Academico'), ('D', 'Deportivo'), ('C', 'Civico'), ('P', 'Pasillos'), ('R', 'Recreativo')], default=' Default Value', max_length=1)),
                ('ubicacion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(default=' Default Value', upload_to='escenarios')),
                ('estado', models.CharField(choices=[('O', 'Ocupado'), ('D', 'Disponible')], default='Default Value', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('capacidad_evento', models.IntegerField(null=True)),
                ('tipo_evento', models.CharField(choices=[('', 'Selecciona'), ('A', 'Academico'), ('D', 'Deportivo'), ('CRA', 'Cultural'), ('C', 'Civico'), ('R', 'Recreativo'), ('CAP', 'Capacitacion')], max_length=3)),
                ('objetivo', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('medio_difusion', models.FileField(upload_to='')),
                ('req_internet', models.BooleanField()),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Escenario')),
            ],
        ),
        migrations.CreateModel(
            name='ImgEscenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.ImageField(default=' Default Value', upload_to='escenarios')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Escenario')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad_equipo', models.CharField(choices=[('P', 'Propio'), ('I', 'Institucion')], default='Default Value', max_length=1)),
                ('tipo_equipo', models.CharField(choices=[('L', 'Laptop'), ('M', 'MacBook')], default='Default Value', max_length=1)),
                ('tipo_equipoAudio', models.CharField(choices=[('M', 'Microfono'), ('B', 'Bocina')], default='Default Value', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.ImgEscenario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Evento'),
        ),
    ]
