# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escenario',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='escenario',
            name='estado',
            field=models.CharField(choices=[('O', 'Ocupado'), ('D', 'Disponible')], default='Disponible', max_length=1),
        ),
        migrations.AlterField(
            model_name='escenario',
            name='tipo_escenario',
            field=models.CharField(choices=[('O', 'Operativo'), ('A', 'Academico'), ('D', 'Deportivo'), ('C', 'Civico'), ('P', 'Pasillos'), ('R', 'Recreativo')], default='Default Value', max_length=1),
        ),
    ]
